# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-11 11:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alias_packets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('existed_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('alias_name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'alias_packets',
            },
        ),
        migrations.CreateModel(
            name='Alias_Widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_widget_name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'alias_widget',
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epoch', models.CharField(max_length=40, verbose_name='selected_date')),
                ('text', models.TextField()),
                ('key', models.CharField(max_length=512, null=True)),
                ('dt_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'annotations',
            },
        ),
        migrations.CreateModel(
            name='Authoringtable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(default='', max_length=255)),
                ('table_schema', models.CharField(default='', max_length=255)),
                ('sheet_field', models.CharField(default='', max_length=255)),
                ('table_type', models.CharField(choices=[('raw_table', 'Raw_table'), ('external_error', 'External_error'), ('internal_error', 'Internal_error'), ('target', 'targets'), ('other', 'Other'), ('internal_external', 'Error')], default='other', max_length=30)),
            ],
            options={
                'db_table': 'authoring_table',
            },
        ),
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'center',
            },
        ),
        migrations.CreateModel(
            name='Centermanager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Center')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'center_manager',
            },
        ),
        migrations.CreateModel(
            name='ChartType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_type', models.CharField(max_length=512)),
            ],
            options={
                'db_table': 'chart_type',
            },
        ),
        migrations.CreateModel(
            name='Color_Mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_project', models.CharField(blank=True, max_length=255)),
                ('work_packet', models.CharField(blank=True, max_length=255)),
                ('sub_packet', models.CharField(blank=True, max_length=255)),
                ('color_code', models.CharField(max_length=255)),
                ('center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Center')),
            ],
            options={
                'db_table': 'color_mappping',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_drilldown', models.BooleanField(default=None)),
                ('center', models.ManyToManyField(null=True, to='api.Center')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='media/preprocessing/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'upload_table',
            },
        ),
        migrations.CreateModel(
            name='Externalerrors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_project', models.CharField(blank=True, max_length=255)),
                ('work_packet', models.CharField(max_length=255)),
                ('sub_packet', models.CharField(blank=True, max_length=255)),
                ('type_error', models.CharField(blank=True, max_length=255)),
                ('sub_error_count', models.CharField(blank=True, max_length=512)),
                ('error_types', models.CharField(blank=True, max_length=512)),
                ('error_values', models.CharField(blank=True, max_length=512)),
                ('audited_errors', models.IntegerField(blank=True, default=0)),
                ('total_errors', models.IntegerField(default=0, verbose_name='total_errors')),
                ('date', models.DateField()),
                ('employee_id', models.CharField(blank=True, max_length=255)),
                ('center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Center')),
            ],
            options={
                'db_table': 'external_error',
            },
        ),
        migrations.CreateModel(
            name='ExternalerrorsAuthoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_project', models.CharField(blank=True, max_length=255)),
                ('work_packet', models.CharField(max_length=255)),
                ('sub_packet', models.CharField(blank=True, max_length=255)),
                ('type_error', models.CharField(blank=True, max_length=255)),
                ('audited_errors', models.CharField(blank=True, max_length=255, verbose_name='Audited_errors')),
                ('total_errors', models.CharField(default=0, max_length=255, verbose_name='total_errors')),
                ('error_category', models.CharField(blank=True, max_length=255)),
                ('error_count', models.CharField(blank=True, max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('employee_id', models.CharField(blank=True, max_length=255)),
                ('sheet_name', models.CharField(default='', max_length=255)),
                ('total_errors_require', models.BooleanField(default=None)),
                ('center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Center')),
            ],
            options={
                'db_table': 'externalerrors_authoring',
            },
        ),
        migrations.CreateModel(
            name='Headcount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sub_project', models.CharField(blank=True, max_length=255)),
                ('work_packet', models.CharField(blank=True, max_length=255)),
                ('sub_packet', models.CharField(blank=True, max_length=255)),
                ('billable_hc', models.FloatField(db_index=True, max_length=255)),
                ('billable_agents', models.FloatField(db_index=True, max_length=255)),
                ('buffer_agents', models.FloatField(db_index=True, max_length=255)),
                ('qc_or_qa', models.FloatField(db_index=True, max_length=255)),
                ('teamlead', models.FloatField(blank=True, db_index=True, max_length=255)),
                ('trainees_and_trainers', models.FloatField(blank=True, db_index=True, max_length=255)),
                ('managers', models.FloatField(blank=True, db_index=True, max_length=255)),
                ('mis', models.FloatField(blank=True, db_index=True, max_length=255)),
                ('center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Center')),
            ],
            options={
                'db_table': 'headcount_table',
            },
        ),
        migrations.CreateModel(
            name='HeadcountAuthoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=255)),
                ('sub_project', models.CharField(blank=True, db_index=True, max_length=255)),
                ('work_packet', models.CharField(blank=True, db_index=True, max_length=255)),
                ('sub_packet', models.CharField(blank=True, db_index=True, max_length=255)),
                ('billable_hc', models.CharField(db_index=True, max_length=255)),
                ('billable_agents', models.CharField(db_index=True, max_length=255)),
                ('buffer_agents', models.CharField(db_index=True, max_length=255)),
                ('qc_or_qa', models.CharField(db_index=True, max_length=255)),
                ('teamlead', models.CharField(db_index=True, max_length=255)),
                ('trainees_and_trainers', models.CharField(db_index=True, max_length=255)),
                ('managers', models.CharField(db_index=True, max_length=255)),
                ('mis', models.CharField(db_index=True, max_length=255)),
                ('sheet_name', models.CharField(default='', max_length=255)),
                ('center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Center')),
            ],
            options={
                'db_table': 'headcount_authoring',
            },
        ),
        migrations.CreateModel(
            name='HRMAttendance',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('empid', models.CharField(max_length=20)),
                ('A01', models.CharField(max_length=5)),
                ('A02', models.CharField(max_length=5)),
                ('A03', models.CharField(max_length=5)),
                ('A04', models.CharField(max_length=5)),
                ('A05', models.CharField(max_length=5)),
                ('A06', models.CharField(max_length=5)),
                ('A07', models.CharField(max_length=5)),
                ('A08', models.CharField(max_length=5)),
                ('A09', models.CharField(max_length=5)),
                ('A10', models.CharField(max_length=5)),
                ('A11', models.CharField(max_length=5)),
                ('A12', models.CharField(max_length=5)),
                ('A13', models.CharField(max_length=5)),
                ('A14', models.CharField(max_length=5)),
                ('A15', models.CharField(max_length=5)),
                ('A16', models.CharField(max_length=5)),
                ('A17', models.CharField(max_length=5)),
                ('A18', models.CharField(max_length=5)),
                ('A19', models.CharField(max_length=5)),
                ('A20', models.CharField(max_length=5)),
                ('A21', models.CharField(max_length=5)),
                ('A22', models.CharField(max_length=5)),
                ('A23', models.CharField(max_length=5)),
                ('A24', models.CharField(max_length=5)),
                ('A25', models.CharField(max_length=5)),
                ('A26', models.CharField(max_length=5)),
                ('A27', models.CharField(max_length=5)),
                ('A28', models.CharField(max_length=5)),
                ('A29', models.CharField(max_length=5)),
                ('A30', models.CharField(max_length=5)),
                ('A31', models.CharField(max_length=5)),
                ('month', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'hrm_attendance',
            },
        ),
        migrations.CreateModel(
            name='HRMEmployeeProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.CharField(max_length=10)),
                ('team', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'hrm_employee_process',
            },
        ),
        migrations.CreateModel(
            name='HRMEmployeeReportingPerson',
            fields=[
                ('empid', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('reporting_person', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'hrm_employee_reportingperson',
            },
        ),
        migrations.CreateModel(
            name='HRMEmployeeResignation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.CharField(max_length=15)),
                ('relivingtype', models.CharField(max_length=25)),
                ('resignedon', models.CharField(max_length=10)),
                ('noticeperiod', models.CharField(max_length=5)),
                ('ulsince', models.CharField(max_length=10)),
                ('memoon', models.CharField(max_length=10)),
                ('raplymemo', models.CharField(max_length=5)),
                ('lastday', models.CharField(max_length=10)),
                ('idcard', models.CharField(max_length=10)),
                ('resion', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=5)),
                ('rdate', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'hrm_employee_resignation',
            },
        ),
        migrations.CreateModel(
            name='HRMMovementTracker',
            fields=[
                ('recordid', models.AutoField(primary_key=True, serialize=False)),
                ('empid', models.CharField(max_length=20)),
                ('oldteam', models.CharField(max_length=100)),
                ('oldscope', models.CharField(max_length=100)),
                ('oldrole', models.CharField(max_length=100)),
                ('newteam', models.CharField(max_length=100)),
                ('newscope', models.CharField(max_length=100)),
                ('newrole', models.CharField(max_length=100)),
                ('movedate', models.DateField()),
                ('reason', models.CharField(max_length=500)),
                ('approval', models.CharField(max_length=3)),
                ('hc_tracker', models.CharField(max_length=3)),
                ('misreport', models.CharField(max_length=3)),
                ('e4e', models.CharField(max_length=3)),
                ('boimetric', models.CharField(max_length=3)),
                ('domain', models.CharField(max_length=3)),
                ('teamdata', models.CharField(max_length=3)),
                ('risedfrom', models.CharField(max_length=150)),
                ('approvedby', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'hrm_movement_tracker',
            },
        ),
        migrations.CreateModel(
            name='Incomingerror',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sub_project', models.CharField(blank=True, db_index=True, max_length=255)),
                ('work_packet', models.CharField(db_index=True, max_length=255)),
                ('sub_packet', models.CharField(blank=True, db_index=True, max_length=255)),
                ('error_values', models.IntegerField()),
                ('center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Center')),
            ],
            options={
                'db_table': 'incoming_error',
            },
        ),
        migrations.CreateModel(
            name='IncomingerrorAuthoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=255)),
                ('sub_project', models.CharField(blank=True, max_length=255)),
                ('work_packet', models.CharField(blank=True, max_length=255)),
                ('sub_packet', models.CharField(blank=True, max_length=255)),
                ('error_values', models.CharField(blank=True, max_length=255)),
                ('sheet_name', models.CharField(default='', max_length=255)),
                ('center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Center')),
            ],
            options={
                'db_table': 'incoming_error_authoring',
            },
        ),
        migrations.CreateModel(
            name='Internalerrors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_project', models.CharField(blank=True, db_index=True, max_length=255)),
                ('work_packet', models.CharField(db_index=True, max_length=255)),
                ('sub_packet', models.CharField(blank=True, db_index=True, max_length=255)),
                ('type_error', models.CharField(blank=True, max_length=255)),
                ('sub_error_count', models.CharField(blank=True, max_length=512)),
                ('error_types', models.CharField(blank=True, max_length=512)),
                ('error_values', models.CharField(blank=True, max_length=512)),
                ('audited_errors', models.IntegerField(blank=True, default=0)),
                ('total_errors', models.IntegerField(default=0, verbose_name='total_errors')),
                ('date', models.DateField()),
                ('employee_id', models.CharField(blank=True, max_length=255)),
                ('center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Center')),
            ],
            options={
                'db_table': 'internal_error',
            },
        ),
        migrations.CreateModel(
            name='InternalerrorsAuthoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_project', models.CharField(blank=True, max_length=255)),
                ('work_packet', models.CharField(max_length=255)),
                ('sub_packet', models.CharField(blank=True, max_length=255)),
                ('audited_errors', models.CharField(blank=True, max_length=255, verbose_name='Audited_errors')),
                ('total_errors', models.CharField(default=0, max_length=255, verbose_name='total_errors')),
                ('type_error', models.CharField(blank=True, max_length=255)),
                ('error_category', models.CharField(blank=True, max_length=255)),
                ('error_count', models.CharField(blank=True, max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('employee_id', models.CharField(blank=True, max_length=255)),
                ('sheet_name', models.CharField(default='', max_length=255)),
                ('total_errors_require', models.BooleanField(default=None)),
                ('center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Center')),
            ],
            options={
                'db_table': 'internalerrors_authoring',
            },
        ),
        migrations.CreateModel(
            name='Nextwealthmanager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center', models.ManyToManyField(to='api.Center')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nextwealthmanager',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_key', models.CharField(max_length=40)),
                ('status', models.BooleanField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('days_week', models.IntegerField(default=5)),
                ('days_month', models.IntegerField(default=21)),
                ('project_db_handling', models.CharField(choices=[('update', 'Update'), ('aggregate', 'Aggregate'), ('ignore', 'Ignore')], default='ignore', max_length=30)),
                ('sub_project_check', models.BooleanField(default=None)),
                ('center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Center')),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='RawTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=255)),
                ('sub_project', models.CharField(blank=True, db_index=True, max_length=255)),
                ('work_packet', models.CharField(db_index=True, max_length=255)),
                ('sub_packet', models.CharField(blank=True, db_index=True, max_length=255)),
                ('per_hour', models.IntegerField(default=0, max_length=255)),
                ('per_day', models.IntegerField(db_index=True, default=0, max_length=255)),
                ('date', models.DateField()),
                ('norm', models.IntegerField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Center')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Project')),
            ],
            options={
                'db_table': 'raw_table',
            },
        ),
        migrations.CreateModel(
            name='RawtableAuthoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=255)),
                ('sub_project', models.CharField(blank=True, max_length=255)),
                ('work_packet', models.CharField(max_length=255)),
                ('sub_packet', models.CharField(blank=True, max_length=255)),
                ('per_hour', models.CharField(blank=True, max_length=255)),
                ('per_day', models.CharField(blank=True, max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('norm', models.CharField(blank=True, max_length=255)),
                ('sheet_name', models.CharField(default='', max_length=255)),
                ('ignorable_fileds', models.CharField(blank=True, default='', max_length=255)),
                ('center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Center')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Project')),
            ],
            options={
                'db_table': 'rawtable_authoring',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_name', models.CharField(db_index=True, max_length=255)),
                ('review_agenda', models.TextField(blank=True, null=True)),
                ('review_date', models.DateTimeField(db_index=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('updation_date', models.DateTimeField(auto_now=True)),
                ('review_type', models.CharField(blank=True, max_length=16)),
                ('venue', models.TextField(blank=True, null=True)),
                ('bridge', models.CharField(blank=True, max_length=64)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Project')),
            ],
            options={
                'db_table': 'review_system',
            },
        ),
        migrations.CreateModel(
            name='ReviewFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='reviews/%Y%m')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('updation_date', models.DateTimeField(auto_now=True)),
                ('original_file_name', models.CharField(max_length=64)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Review')),
            ],
            options={
                'db_table': 'review_files',
            },
        ),
        migrations.CreateModel(
            name='ReviewMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_mail', models.BooleanField(db_index=True, default=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Review')),
            ],
            options={
                'db_table': 'review_members',
            },
        ),
        migrations.CreateModel(
            name='Targets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('sub_project', models.CharField(blank=True, db_index=True, max_length=255)),
                ('work_packet', models.CharField(db_index=True, max_length=255)),
                ('sub_packet', models.CharField(blank=True, db_index=True, max_length=255)),
                ('target', models.IntegerField()),
                ('fte_target', models.IntegerField(default=0)),
                ('target_type', models.CharField(blank=True, max_length=255)),
                ('target_value', models.IntegerField(default=0)),
                ('center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Center')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Project')),
            ],
            options={
                'db_table': 'target_table',
            },
        ),
        migrations.CreateModel(
            name='TargetsAuthoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.CharField(max_length=255)),
                ('to_date', models.CharField(max_length=255)),
                ('sub_project', models.CharField(blank=True, max_length=255)),
                ('work_packet', models.CharField(blank=True, max_length=255)),
                ('sub_packet', models.CharField(blank=True, max_length=255)),
                ('target', models.CharField(max_length=125)),
                ('fte_target', models.CharField(blank=True, max_length=125)),
                ('target_type', models.CharField(blank=True, max_length=255)),
                ('target_value', models.CharField(blank=True, max_length=125)),
                ('sheet_name', models.CharField(default='', max_length=255)),
                ('center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Center')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Project')),
            ],
            options={
                'db_table': 'targets_authoring',
            },
        ),
        migrations.CreateModel(
            name='TatAuthoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_project', models.CharField(blank=True, max_length=255)),
                ('work_packet', models.CharField(blank=True, max_length=255)),
                ('sub_packet', models.CharField(blank=True, max_length=255)),
                ('received_date', models.CharField(blank=True, max_length=255)),
                ('total_received', models.CharField(blank=True, max_length=255)),
                ('scan_date', models.CharField(blank=True, max_length=255)),
                ('completed_date', models.CharField(blank=True, max_length=255)),
                ('met_count', models.CharField(blank=True, max_length=125)),
                ('non_met_count', models.CharField(blank=True, max_length=125)),
                ('tat_status', models.CharField(blank=True, max_length=255)),
                ('sheet_name', models.CharField(default='', max_length=255)),
                ('center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Center')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Project')),
            ],
            options={
                'db_table': 'tat_authoring',
            },
        ),
        migrations.CreateModel(
            name='TatTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_project', models.CharField(blank=True, max_length=255)),
                ('work_packet', models.CharField(max_length=255)),
                ('sub_packet', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField()),
                ('completed_date', models.DateField(null=True)),
                ('scan_date', models.DateField(null=True)),
                ('total_received', models.IntegerField()),
                ('met_count', models.IntegerField()),
                ('non_met_count', models.IntegerField(blank=True)),
                ('tat_status', models.CharField(max_length=255)),
                ('center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Center')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Project')),
            ],
            options={
                'db_table': 'tats_table',
            },
        ),
        migrations.CreateModel(
            name='TeamLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Center')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Project')),
            ],
            options={
                'db_table': 'agent',
            },
        ),
        migrations.CreateModel(
            name='UploadAuthoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=255)),
                ('sub_project', models.CharField(blank=True, max_length=255)),
                ('target', models.CharField(blank=True, max_length=255)),
                ('upload', models.CharField(blank=True, max_length=255)),
                ('sheet_name', models.CharField(default='', max_length=255)),
                ('center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Center')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Project')),
            ],
            options={
                'db_table': 'upload_authoring',
            },
        ),
        migrations.CreateModel(
            name='UploadDataTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sub_project', models.CharField(blank=True, max_length=255)),
                ('target', models.IntegerField(default=0)),
                ('upload', models.IntegerField()),
                ('center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Center')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Project')),
            ],
            options={
                'db_table': 'upload_data_table',
            },
        ),
        migrations.CreateModel(
            name='Widgets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_name', models.CharField(db_index=True, max_length=255)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('api', models.CharField(blank=True, max_length=255, null=True)),
                ('opt', models.CharField(max_length=225)),
                ('id_num', models.IntegerField()),
                ('day_type_widget', models.BooleanField(default=None)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('chart_type_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ChartType')),
            ],
            options={
                'db_table': 'widgets',
            },
        ),
        migrations.CreateModel(
            name='Widgets_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col', models.IntegerField(default=0)),
                ('widget_priority', models.IntegerField()),
                ('is_display', models.BooleanField(default=None)),
                ('is_drilldown', models.BooleanField(default=None)),
                ('User_Group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Center')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Project')),
                ('widget_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Widgets')),
            ],
            options={
                'db_table': 'Widgets_group',
            },
        ),
        migrations.CreateModel(
            name='Worktrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sub_project', models.CharField(blank=True, db_index=True, max_length=255)),
                ('work_packet', models.CharField(db_index=True, max_length=255)),
                ('sub_packet', models.CharField(blank=True, db_index=True, max_length=255)),
                ('opening', models.IntegerField()),
                ('received', models.IntegerField()),
                ('non_workable_count', models.IntegerField(blank=True, default=0)),
                ('completed', models.IntegerField()),
                ('closing_balance', models.IntegerField()),
                ('center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Center')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Project')),
            ],
            options={
                'db_table': 'worktrack_table',
            },
        ),
        migrations.CreateModel(
            name='WorktrackAuthoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=255)),
                ('sub_project', models.CharField(blank=True, max_length=255)),
                ('work_packet', models.CharField(max_length=255)),
                ('sub_packet', models.CharField(blank=True, max_length=255)),
                ('opening', models.CharField(max_length=125)),
                ('received', models.CharField(max_length=125)),
                ('non_workable_count', models.CharField(blank=True, max_length=125)),
                ('completed', models.CharField(max_length=125)),
                ('closing_balance', models.CharField(max_length=125)),
                ('sheet_name', models.CharField(default='', max_length=255)),
                ('center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Center')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Project')),
            ],
            options={
                'db_table': 'worktrack_authornig',
            },
        ),
        migrations.AddField(
            model_name='review',
            name='team_lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.TeamLead'),
        ),
        migrations.AddField(
            model_name='rawtable',
            name='team_lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.TeamLead'),
        ),
        migrations.AddField(
            model_name='internalerrorsauthoring',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Project'),
        ),
        migrations.AddField(
            model_name='internalerrors',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Project'),
        ),
        migrations.AddField(
            model_name='incomingerrorauthoring',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Project'),
        ),
        migrations.AddField(
            model_name='incomingerror',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Project'),
        ),
        migrations.AddField(
            model_name='headcountauthoring',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Project'),
        ),
        migrations.AddField(
            model_name='headcount',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Project'),
        ),
        migrations.AddField(
            model_name='externalerrorsauthoring',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Project'),
        ),
        migrations.AddField(
            model_name='externalerrors',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Project'),
        ),
        migrations.AddField(
            model_name='customer',
            name='project',
            field=models.ManyToManyField(null=True, to='api.Project'),
        ),
        migrations.AddField(
            model_name='color_mapping',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Project'),
        ),
        migrations.AddField(
            model_name='authoringtable',
            name='center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Center'),
        ),
        migrations.AddField(
            model_name='authoringtable',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Project'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Center'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='chart_type_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ChartType'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='annotation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Project'),
        ),
        migrations.AddField(
            model_name='alias_widget',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Project'),
        ),
        migrations.AddField(
            model_name='alias_widget',
            name='widget_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Widgets'),
        ),
        migrations.AddField(
            model_name='alias_packets',
            name='widget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Alias_Widget'),
        ),
        migrations.AlterIndexTogether(
            name='worktrackauthoring',
            index_together=set([('project', 'center')]),
        ),
        migrations.AlterIndexTogether(
            name='worktrack',
            index_together=set([('project', 'center', 'sub_project', 'work_packet', 'sub_packet', 'date')]),
        ),
        migrations.AlterIndexTogether(
            name='widgets_group',
            index_together=set([('project', 'center')]),
        ),
        migrations.AlterIndexTogether(
            name='widgets',
            index_together=set([('name', 'config_name')]),
        ),
        migrations.AlterIndexTogether(
            name='targetsauthoring',
            index_together=set([('project', 'center')]),
        ),
        migrations.AlterIndexTogether(
            name='targets',
            index_together=set([('project', 'center', 'sub_project', 'work_packet', 'sub_packet', 'from_date', 'to_date')]),
        ),
        migrations.AlterUniqueTogether(
            name='reviewfiles',
            unique_together=set([('review', 'file_name')]),
        ),
        migrations.AlterIndexTogether(
            name='reviewfiles',
            index_together=set([('review', 'file_name')]),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set([('review_name', 'project', 'review_date')]),
        ),
        migrations.AlterIndexTogether(
            name='rawtableauthoring',
            index_together=set([('project', 'center')]),
        ),
        migrations.AlterIndexTogether(
            name='rawtable',
            index_together=set([('project', 'center', 'sub_project', 'work_packet', 'sub_packet', 'date')]),
        ),
        migrations.AlterIndexTogether(
            name='project',
            index_together=set([('name', 'center')]),
        ),
        migrations.AlterIndexTogether(
            name='internalerrorsauthoring',
            index_together=set([('project', 'center')]),
        ),
        migrations.AlterIndexTogether(
            name='internalerrors',
            index_together=set([('project', 'center', 'sub_project', 'work_packet', 'sub_packet', 'date')]),
        ),
        migrations.AlterIndexTogether(
            name='headcountauthoring',
            index_together=set([('project', 'center')]),
        ),
        migrations.AlterIndexTogether(
            name='headcount',
            index_together=set([('project', 'center', 'sub_project', 'work_packet', 'sub_packet', 'date')]),
        ),
        migrations.AlterIndexTogether(
            name='externalerrorsauthoring',
            index_together=set([('project', 'center')]),
        ),
        migrations.AlterIndexTogether(
            name='externalerrors',
            index_together=set([('project', 'center', 'sub_project', 'work_packet', 'sub_packet', 'date')]),
        ),
        migrations.AlterIndexTogether(
            name='color_mapping',
            index_together=set([('project', 'center', 'sub_project', 'work_packet', 'sub_packet')]),
        ),
        migrations.AlterIndexTogether(
            name='annotation',
            index_together=set([('project', 'center')]),
        ),
        migrations.AlterIndexTogether(
            name='alias_widget',
            index_together=set([('project', 'widget_name')]),
        ),
    ]
