# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-11 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='center',
            field=models.ManyToManyField(db_index=True, null=True, to='api.Center'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='project',
            field=models.ManyToManyField(db_index=True, null=True, to='api.Project'),
        ),
        migrations.AlterField(
            model_name='reviewfiles',
            name='file_name',
            field=models.FileField(db_index=True, upload_to='reviews/%Y%m'),
        ),
        migrations.AlterField(
            model_name='targets',
            name='target_type',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterIndexTogether(
            name='annotation',
            index_together=set([('epoch', 'created_by', 'key'), ('project', 'center')]),
        ),
        migrations.AlterIndexTogether(
            name='authoringtable',
            index_together=set([('project', 'center')]),
        ),
        migrations.AlterIndexTogether(
            name='externalerrors',
            index_together=set([('project', 'center', 'sub_project', 'date'), ('project', 'center'), ('project', 'center', 'work_packet', 'date'), ('project', 'center', 'employee_id', 'date', 'sub_project'), ('project', 'center', 'sub_project', 'work_packet', 'sub_packet', 'employee_id', 'date'), ('project', 'center', 'employee_id', 'date', 'work_packet', 'sub_packet'), ('project', 'center', 'sub_project', 'work_packet', 'sub_packet', 'date'), ('project', 'center', 'sub_packet', 'date'), ('center', 'project', 'date', 'work_packet', 'sub_packet'), ('project', 'center', 'date', 'sub_project', 'work_packet'), ('project', 'center', 'date')]),
        ),
        migrations.AlterIndexTogether(
            name='headcount',
            index_together=set([('project', 'center', 'sub_project', 'work_packet', 'sub_packet', 'date'), ('project', 'center', 'date')]),
        ),
        migrations.AlterIndexTogether(
            name='incomingerror',
            index_together=set([('project', 'center', 'work_packet', 'sub_packet', 'date'), ('project', 'center', 'work_packet', 'date'), ('project', 'center', 'sub_project', 'work_packet', 'sub_packet', 'date'), ('project', 'center', 'sub_packet', 'date')]),
        ),
        migrations.AlterIndexTogether(
            name='internalerrors',
            index_together=set([('project', 'center'), ('project', 'center', 'sub_project', 'work_packet', 'sub_packet', 'employee_id', 'date'), ('project', 'center', 'date', 'work_packet'), ('project', 'center', 'work_packet'), ('project', 'center', 'employee_id', 'date'), ('project', 'center', 'date', 'sub_project'), ('project', 'center', 'sub_project', 'work_packet', 'sub_packet', 'date'), ('center', 'project', 'date', 'work_packet', 'sub_packet'), ('project', 'center', 'date', 'sub_project', 'work_packet'), ('project', 'center', 'date'), ('project', 'center', 'sub_project')]),
        ),
        migrations.AlterIndexTogether(
            name='project',
            index_together=set([('name', 'center'), ('name', 'sub_project_check', 'center')]),
        ),
        migrations.AlterIndexTogether(
            name='rawtable',
            index_together=set([('employee_id', 'date', 'work_packet'), ('project', 'work_packet', 'date'), ('project', 'sub_project', 'work_packet', 'sub_packet', 'date', 'center'), ('project', 'center'), ('project', 'center', 'date', 'work_packet', 'sub_packet'), ('project', 'center', 'date', 'work_packet'), ('project', 'sub_project', 'date'), ('project', 'sub_project', 'work_packet', 'date'), ('employee_id', 'date', 'work_packet', 'sub_packet'), ('employee_id', 'date', 'work_packet', 'sub_project'), ('project', 'center', 'date'), ('project', 'sub_project', 'work_packet', 'sub_packet', 'employee_id', 'date', 'center'), ('project', 'center', 'date', 'work_packet', 'employee_id'), ('project', 'center', 'date', 'sub_project')]),
        ),
        migrations.AlterIndexTogether(
            name='review',
            index_together=set([('project', 'review_name', 'review_date')]),
        ),
        migrations.AlterIndexTogether(
            name='reviewfiles',
            index_together=set([('review', 'file_name'), ('original_file_name', 'review')]),
        ),
        migrations.AlterIndexTogether(
            name='targets',
            index_together=set([('project', 'work_packet', 'sub_project', 'from_date', 'to_date', 'target_type', 'center'), ('project', 'center', 'work_packet', 'from_date', 'to_date'), ('project', 'center', 'sub_project', 'work_packet', 'sub_packet', 'from_date', 'to_date')]),
        ),
        migrations.AlterIndexTogether(
            name='tattable',
            index_together=set([('project', 'center', 'sub_project', 'work_packet', 'sub_packet', 'date'), ('project', 'center', 'date')]),
        ),
        migrations.AlterIndexTogether(
            name='teamlead',
            index_together=set([('project', 'center')]),
        ),
        migrations.AlterIndexTogether(
            name='uploaddatatable',
            index_together=set([('project', 'sub_project', 'center', 'date'), ('project', 'center', 'date')]),
        ),
        migrations.AlterIndexTogether(
            name='widgets_group',
            index_together=set([('User_Group', 'project', 'center'), ('project', 'center')]),
        ),
        migrations.AlterIndexTogether(
            name='worktrack',
            index_together=set([('project', 'center', 'sub_project', 'date'), ('project', 'center'), ('project', 'center', 'work_packet', 'date'), ('project', 'center', 'sub_packet', 'date'), ('project', 'center', 'sub_project', 'work_packet', 'sub_packet', 'date'), ('project', 'center', 'date')]),
        ),
    ]
