# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-11 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170811_1243'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='annotation',
            unique_together=set([('project', 'center', 'epoch', 'key')]),
        ),
    ]
