# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-21 07:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170911_1604'),
        ('api', '0003_auto_20170908_0600'),
    ]

    operations = [
    ]
