# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-28 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(choices=[('backoffice', 0), ('voice', 1)], db_index=True, default=0, max_length=255),
        ),
    ]
