# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-10-04 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_project_is_voice'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgets_group',
            name='display_value',
            field=models.BooleanField(default=None),
        ),
    ]
