# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-10-12 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_widgets_group_display_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_display',
            field=models.BooleanField(default=False),
        ),
    ]
