# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-10-12 05:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_project_is_display'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='is_display',
            new_name='display_value',
        ),
    ]
