# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-10-23 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20171012_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widgets_group',
            name='display_value',
            field=models.BooleanField(default=True),
        ),
    ]
