# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-10-23 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_widgets_group_display_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgets_group',
            name='display_value',
            field=models.BooleanField(default=True),
        ),
    ]
