# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-01-04 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_widgets_group_display_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='chart_id',
            field=models.IntegerField(default=0),
        ),
    ]
