# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-01-16 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_widgets_group_display_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='targets',
            name='target_method',
            field=models.CharField(blank=True, db_index=True, max_length=125),
        ),
        migrations.AddField(
            model_name='targetsauthoring',
            name='target_method',
            field=models.CharField(blank=True, max_length=125),
        ),
    ]
