# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-03-06 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_annotation_chart_id'),
        ('api', '0014_auto_20180116_0902'),
    ]

    operations = [
    ]
