# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-09-04 12:13
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0015_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='AHTIndividual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('emp_name', models.CharField(blank=True, max_length=255)),
                ('sub_project', models.CharField(blank=True, max_length=255)),
                ('work_packet', models.CharField(blank=True, max_length=255)),
                ('sub_packet', models.CharField(blank=True, max_length=255)),
                ('AHT', models.FloatField(default=0, max_length=125)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Center')),
            ],
            options={
                'db_table': 'AHT_individual',
            },
        ),
        migrations.CreateModel(
            name='AHTIndividualAuthoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=255)),
                ('emp_name', models.CharField(blank=True, max_length=255)),
                ('sub_project', models.CharField(blank=True, max_length=255)),
                ('work_packet', models.CharField(blank=True, max_length=255)),
                ('sub_packet', models.CharField(blank=True, max_length=255)),
                ('AHT', models.CharField(max_length=255)),
                ('sheet_name', models.CharField(default='AHT Individual', max_length=255)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Center')),
            ],
            options={
                'db_table': 'AHT_individual_authoring',
            },
        ),
        migrations.CreateModel(
            name='AHTTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sub_project', models.CharField(blank=True, max_length=255)),
                ('work_packet', models.CharField(blank=True, max_length=255)),
                ('sub_packet', models.CharField(blank=True, max_length=255)),
                ('AHT', models.FloatField(default=0, max_length=125)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Center')),
            ],
            options={
                'db_table': 'AHT_team',
            },
        ),
        migrations.CreateModel(
            name='AHTTeamAuthoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=255)),
                ('sub_project', models.CharField(blank=True, max_length=255)),
                ('work_packet', models.CharField(blank=True, max_length=255)),
                ('sub_packet', models.CharField(blank=True, max_length=255)),
                ('AHT', models.CharField(max_length=255)),
                ('sheet_name', models.CharField(default='AHT Team', max_length=255)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Center')),
            ],
            options={
                'db_table': 'AHT_team_authoring',
            },
        ),
        migrations.CreateModel(
            name='OneSignal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=125)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'onesignal_deviceid',
            },
        ),
        migrations.RemoveField(
            model_name='tatauthoring',
            name='completed_date',
        ),
        migrations.RemoveField(
            model_name='tatauthoring',
            name='received_date',
        ),
        migrations.RemoveField(
            model_name='tatauthoring',
            name='scan_date',
        ),
        migrations.RemoveField(
            model_name='tattable',
            name='completed_date',
        ),
        migrations.RemoveField(
            model_name='tattable',
            name='scan_date',
        ),
        migrations.AddField(
            model_name='annotation',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='legends_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('bottom', 'Bottom')], default='bottom', max_length=30),
        ),
        migrations.AddField(
            model_name='hrmattendance',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 9, 4, 12, 12, 43, 261979, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hrmemployeeprocess',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 9, 4, 12, 12, 50, 357781, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hrmemployeereportingperson',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hrmmovementtracker',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 9, 4, 12, 13, 3, 637638, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='display_project',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_enable_push',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='no_of_agents',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='project',
            name='no_of_packets',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='tatauthoring',
            name='date',
            field=models.CharField(default='Date', max_length=125),
        ),
        migrations.AddField(
            model_name='teamlead',
            name='display_upload',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='widgets_group',
            name='legends_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('bottom', 'Bottom')], default='bottom', max_length=30),
        ),
        migrations.AlterField(
            model_name='hrmemployeeresignation',
            name='rdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='teamlead',
            name='center',
            field=models.ManyToManyField(null=True, to='api.Center'),
        ),
        migrations.AddField(
            model_name='teamlead',
            name='project',
            field=models.ManyToManyField(null=True, to='api.Project'),
        ),
        migrations.AlterIndexTogether(
            name='teamlead',
            index_together=set([]),
        ),
        migrations.AddField(
            model_name='ahtteamauthoring',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Project'),
        ),
        migrations.AddField(
            model_name='ahtteam',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Project'),
        ),
        migrations.AddField(
            model_name='ahtindividualauthoring',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Project'),
        ),
        migrations.AddField(
            model_name='ahtindividual',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Project'),
        ),
        migrations.RemoveField(
            model_name='teamlead',
            name='center',
        ),
        migrations.RemoveField(
            model_name='teamlead',
            name='project',
        ),
        migrations.AlterIndexTogether(
            name='ahtteam',
            index_together=set([('project', 'center', 'sub_project', 'work_packet', 'date'), ('project', 'center', 'sub_project', 'work_packet', 'sub_packet', 'date'), ('project', 'center', 'date'), ('project', 'center', 'work_packet', 'date')]),
        ),
        migrations.AlterIndexTogether(
            name='ahtindividual',
            index_together=set([('project', 'center', 'work_packet', 'date'), ('project', 'center', 'date', 'work_packet', 'sub_packet', 'emp_name'), ('project', 'center', 'date', 'work_packet', 'emp_name'), ('project', 'center', 'date', 'emp_name'), ('project', 'center', 'date'), ('project', 'center', 'sub_project', 'work_packet', 'sub_packet', 'date'), ('project', 'center', 'sub_project', 'work_packet', 'date'), ('project', 'center', 'date', 'sub_project', 'work_packet', 'sub_packet', 'emp_name')]),
        ),
    ]
