# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-09-04 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20180904_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sub_project', models.CharField(blank=True, max_length=255)),
                ('work_packet', models.CharField(blank=True, max_length=255)),
                ('sub_packet', models.CharField(blank=True, max_length=255)),
                ('data_entry_volume', models.IntegerField(default=0)),
                ('data_entry_done_aht', models.FloatField(default=0, max_length=500)),
                ('low_volume', models.IntegerField(default=0)),
                ('medium_volume', models.IntegerField(default=0)),
                ('high_volume', models.IntegerField(default=0)),
                ('low_aht', models.FloatField(default=0, max_length=500)),
                ('medium_aht', models.FloatField(default=0, max_length=500)),
                ('high_aht', models.FloatField(default=0, max_length=500)),
                ('pre_populated_volume', models.IntegerField(default=0, max_length=100000)),
                ('pre_populated_aht', models.FloatField(max_length=500)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Center')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Project')),
            ],
            options={
                'db_table': 'Customer_risk_table',
                'verbose_name_plural': 'C_Risk',
            },
        ),
        migrations.CreateModel(
            name='Risk_authoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=255)),
                ('sub_project', models.CharField(blank=True, max_length=255)),
                ('work_packet', models.CharField(blank=True, max_length=255)),
                ('sub_packet', models.CharField(blank=True, max_length=255)),
                ('data_entry_volume', models.CharField(blank=True, max_length=255)),
                ('data_entry_done_aht', models.CharField(blank=True, max_length=255)),
                ('low_volume', models.CharField(blank=True, max_length=255)),
                ('medium_volume', models.CharField(blank=True, max_length=255)),
                ('high_volume', models.CharField(blank=True, max_length=255)),
                ('low_aht', models.CharField(blank=True, max_length=255)),
                ('medium_aht', models.CharField(blank=True, max_length=255)),
                ('high_aht', models.CharField(blank=True, max_length=255)),
                ('pre_populated_volume', models.CharField(blank=True, max_length=255)),
                ('pre_populated_aht', models.CharField(blank=True, max_length=255)),
                ('sheet_name', models.CharField(default='Risk', max_length=255)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Center')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Project')),
            ],
            options={
                'db_table': 'Customer_risk_authoring',
                'verbose_name_plural': 'C_Risk_authoring',
            },
        ),
        migrations.AddField(
            model_name='teamlead',
            name='center',
            field=models.ManyToManyField(null=True, to='api.Center'),
        ),
        migrations.AddField(
            model_name='teamlead',
            name='project',
            field=models.ManyToManyField(null=True, to='api.Project'),
        ),
    ]
