# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-09-04 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20180904_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='IVR_VCR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sub_project', models.CharField(blank=True, max_length=255)),
                ('work_packet', models.CharField(blank=True, max_length=255)),
                ('sub_packet', models.CharField(blank=True, max_length=255)),
                ('approved_verified', models.IntegerField(default=0)),
                ('grossed_up_one', models.IntegerField()),
                ('grossed_up_two', models.IntegerField()),
                ('count', models.IntegerField()),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Center')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Project')),
            ],
            options={
                'db_table': 'Customer_IVR_VCR',
                'verbose_name_plural': 'C_IVR_VCR',
            },
        ),
        migrations.CreateModel(
            name='IVR_VCR_authoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=255)),
                ('sub_project', models.CharField(blank=True, max_length=255)),
                ('work_packet', models.CharField(blank=True, max_length=255)),
                ('sub_packet', models.CharField(blank=True, max_length=255)),
                ('approved_verified', models.CharField(blank=True, max_length=255)),
                ('grossed_up_one', models.CharField(blank=True, max_length=255)),
                ('grossed_up_two', models.CharField(blank=True, max_length=255)),
                ('count', models.CharField(blank=True, max_length=255)),
                ('sheet_name', models.CharField(default='IVR-VCR', max_length=255)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Center')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Project')),
            ],
            options={
                'db_table': 'Customer_IVR_VCR_authoring',
                'verbose_name_plural': 'C_IVR_VCR_authoring',
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sub_project', models.CharField(blank=True, max_length=255)),
                ('work_packet', models.CharField(blank=True, max_length=255)),
                ('sub_packet', models.CharField(blank=True, max_length=255)),
                ('busy', models.TimeField()),
                ('ready', models.TimeField()),
                ('total', models.TimeField()),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Center')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Project')),
            ],
            options={
                'db_table': 'Customer_time_table',
                'verbose_name_plural': 'C_Time',
            },
        ),
        migrations.CreateModel(
            name='Time_authoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sub_project', models.CharField(blank=True, max_length=255)),
                ('work_packet', models.CharField(blank=True, max_length=255)),
                ('sub_packet', models.CharField(blank=True, max_length=255)),
                ('busy', models.CharField(blank=True, max_length=255)),
                ('ready', models.CharField(blank=True, max_length=255)),
                ('total', models.CharField(blank=True, max_length=255)),
                ('sheet_name', models.CharField(default='Time', max_length=255)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Center')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Project')),
            ],
            options={
                'db_table': 'Customer_time_authoring',
                'verbose_name_plural': 'C_Time_authoring',
            },
        ),
    ]
