# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-21 06:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170908_0600'),
        ('voice_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundDailyCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('daily_duration', models.IntegerField(default=0)),
                ('daily_handling_time', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='InboundHourlyCall',
            fields=[
                ('call_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('campaign', models.CharField(blank=True, max_length=255)),
                ('caller_no', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('time_to_answer', models.IntegerField(blank=True, max_length=255)),
                ('end_time', models.DateTimeField()),
                ('talk_time', models.IntegerField(default=0)),
                ('hold_time', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('call_flow', models.CharField(blank=True, max_length=255)),
                ('wrapup_duration', models.IntegerField(default=0)),
                ('disposition', models.CharField(blank=True, max_length=128)),
                ('handling_time', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[(b'Answered', b'Answered'), (b'Unanswered', b'Unanswered')], max_length=50)),
                ('dial_status', models.CharField(default='answered', max_length=128)),
                ('hangup_by', models.CharField(choices=[(b'Caller Disconnect', b'Caller Disconnect'), (b'Agent Disconnect', b'Agent Disconnect')], max_length=32)),
                ('transfer', models.CharField(max_length=255, null=True)),
                ('uui', models.CharField(blank=True, max_length=255)),
                ('comments', models.CharField(blank=True, max_length=255)),
                ('audio_url', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OutboundDailyCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('daily_duration', models.IntegerField(default=0)),
                ('daily_handling_time', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OutboundHourlyCall',
            fields=[
                ('call_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('campaign', models.CharField(blank=True, max_length=255)),
                ('call_type', models.CharField(choices=[(b'Manual', b'Manual'), (b'Automatic', b'Automatic')], max_length=32)),
                ('called_no', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('talk_time', models.IntegerField(default=0)),
                ('hold_time', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('wrapup_duration', models.IntegerField(default=0)),
                ('handling_time', models.IntegerField(default=0)),
                ('call_flow', models.CharField(max_length=255)),
                ('disposition', models.CharField(blank=True, max_length=255)),
                ('dial_status', models.CharField(blank=True, max_length=255)),
                ('customer_dial_status', models.CharField(blank=True, max_length=255)),
                ('agent_dial_status', models.CharField(blank=True, max_length=255)),
                ('hangup_by', models.CharField(choices=[(b'Caller Disconnect', b'Caller Disconnect'), (b'Agent Disconnect', b'Agent Disconnect')], max_length=32)),
                ('transfer', models.CharField(blank=True, max_length=255)),
                ('uui', models.CharField(blank=True, max_length=255)),
                ('comments', models.CharField(blank=True, max_length=255)),
                ('audio_url', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='inbounddailycalls',
            unique_together=set([]),
        ),
        migrations.AlterIndexTogether(
            name='inbounddailycalls',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='inbounddailycalls',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='inboundhourlycalls',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='inboundhourlycalls',
            name='inbound_daily_calls',
        ),
        migrations.RemoveField(
            model_name='inboundhourlycalls',
            name='location',
        ),
        migrations.RemoveField(
            model_name='inboundhourlycalls',
            name='skill',
        ),
        migrations.AlterUniqueTogether(
            name='outbounddailycalls',
            unique_together=set([]),
        ),
        migrations.AlterIndexTogether(
            name='outbounddailycalls',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='outbounddailycalls',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='outboundhourlycalls',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='outboundhourlycalls',
            name='outbound_daily_calls',
        ),
        migrations.RemoveField(
            model_name='inboundhourlycallsauthoring',
            name='UUI',
        ),
        migrations.RemoveField(
            model_name='outboundhourlycallsauthoring',
            name='UUI',
        ),
        migrations.AddField(
            model_name='inboundhourlycallsauthoring',
            name='uui',
            field=models.CharField(default='UUI', max_length=255),
        ),
        migrations.AddField(
            model_name='outboundhourlycallsauthoring',
            name='uui',
            field=models.CharField(default='UUI', max_length=255),
        ),
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='agent',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='api.Project'),
        ),
        migrations.AlterField(
            model_name='agenttransfercall',
            name='call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_tranfer_calls', to='voice_service.InboundHourlyCall'),
        ),
        migrations.AlterField(
            model_name='agenttransfercall',
            name='from_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_agents', to='voice_service.Agent'),
        ),
        migrations.AlterField(
            model_name='agenttransfercall',
            name='to_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_agents', to='voice_service.Agent'),
        ),
        migrations.AlterField(
            model_name='inboundhourlycallsauthoring',
            name='agent',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inboundhourlycallsauthoring',
            name='audio_url',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inboundhourlycallsauthoring',
            name='call_flow',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inboundhourlycallsauthoring',
            name='call_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inboundhourlycallsauthoring',
            name='caller_no',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inboundhourlycallsauthoring',
            name='campaign',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inboundhourlycallsauthoring',
            name='comments',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inboundhourlycallsauthoring',
            name='dial_status',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inboundhourlycallsauthoring',
            name='disposition',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inboundhourlycallsauthoring',
            name='duration',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inboundhourlycallsauthoring',
            name='end_time',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inboundhourlycallsauthoring',
            name='handling_time',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inboundhourlycallsauthoring',
            name='hangup_by',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inboundhourlycallsauthoring',
            name='hold_time',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inboundhourlycallsauthoring',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inboundhourlycallsauthoring',
            name='skill',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inboundhourlycallsauthoring',
            name='start_time',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inboundhourlycallsauthoring',
            name='status',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inboundhourlycallsauthoring',
            name='talk_time',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inboundhourlycallsauthoring',
            name='time_to_answer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inboundhourlycallsauthoring',
            name='transfer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inboundhourlycallsauthoring',
            name='wrapup_duration',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='locationtransfercall',
            name='call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_transfer_calls', to='voice_service.InboundHourlyCall'),
        ),
        migrations.AlterField(
            model_name='locationtransfercall',
            name='from_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_locations', to='api.Center'),
        ),
        migrations.AlterField(
            model_name='locationtransfercall',
            name='to_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_locations', to='api.Center'),
        ),
        migrations.AlterField(
            model_name='outboundhourlycallsauthoring',
            name='agent_dial_status',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='outboundhourlycallsauthoring',
            name='audio_url',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='outboundhourlycallsauthoring',
            name='call_flow',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='outboundhourlycallsauthoring',
            name='call_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='outboundhourlycallsauthoring',
            name='call_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='outboundhourlycallsauthoring',
            name='called_no',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='outboundhourlycallsauthoring',
            name='campaign',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='outboundhourlycallsauthoring',
            name='comments',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='outboundhourlycallsauthoring',
            name='customer_dial_status',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='outboundhourlycallsauthoring',
            name='dial_status',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='outboundhourlycallsauthoring',
            name='disposition',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='outboundhourlycallsauthoring',
            name='duration',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='outboundhourlycallsauthoring',
            name='end_time',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='outboundhourlycallsauthoring',
            name='handling_time',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='outboundhourlycallsauthoring',
            name='hangup_by',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='outboundhourlycallsauthoring',
            name='hold_time',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='outboundhourlycallsauthoring',
            name='start_time',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='outboundhourlycallsauthoring',
            name='talk_time',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='outboundhourlycallsauthoring',
            name='transfer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='outboundhourlycallsauthoring',
            name='wrapup_duration',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='skilltransfercall',
            name='call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_transfer_calls', to='voice_service.InboundHourlyCall'),
        ),
        migrations.AlterField(
            model_name='skilltransfercall',
            name='from_skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_skills', to='voice_service.Skill'),
        ),
        migrations.AlterField(
            model_name='skilltransfercall',
            name='to_skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_skills', to='voice_service.Skill'),
        ),
        migrations.AlterIndexTogether(
            name='agent',
            index_together=set([('name', 'project')]),
        ),
        migrations.AlterIndexTogether(
            name='agenttransfercall',
            index_together=set([('call', 'from_agent', 'to_agent')]),
        ),
        migrations.AlterIndexTogether(
            name='locationtransfercall',
            index_together=set([('call', 'from_location', 'to_location')]),
        ),
        migrations.AlterIndexTogether(
            name='skilltransfercall',
            index_together=set([('call', 'from_skill', 'to_skill')]),
        ),
        migrations.DeleteModel(
            name='InboundDailyCalls',
        ),
        migrations.DeleteModel(
            name='InboundHourlyCalls',
        ),
        migrations.DeleteModel(
            name='OutboundDailyCalls',
        ),
        migrations.DeleteModel(
            name='OutboundHourlyCalls',
        ),
        migrations.AddField(
            model_name='outboundhourlycall',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_agents', to='voice_service.Agent'),
        ),
        migrations.AddField(
            model_name='outboundhourlycall',
            name='outbound_daily_calls',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_calls', to='voice_service.OutboundDailyCall'),
        ),
        migrations.AddField(
            model_name='outbounddailycall',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_daily_calls', to='voice_service.Agent'),
        ),
        migrations.AddField(
            model_name='inboundhourlycall',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_agents', to='voice_service.Agent'),
        ),
        migrations.AddField(
            model_name='inboundhourlycall',
            name='inbound_daily_calls',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_calls', to='voice_service.InboundDailyCall'),
        ),
        migrations.AddField(
            model_name='inboundhourlycall',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_centers', to='api.Center'),
        ),
        migrations.AddField(
            model_name='inboundhourlycall',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_skills', to='voice_service.Skill'),
        ),
        migrations.AddField(
            model_name='inbounddailycall',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_daily_calls', to='voice_service.Agent'),
        ),
        migrations.AlterIndexTogether(
            name='outbounddailycall',
            index_together=set([('agent', 'date')]),
        ),
        migrations.AlterIndexTogether(
            name='inbounddailycall',
            index_together=set([('agent', 'date')]),
        ),
    ]
