# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-01-16 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentperformance',
            name='date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='agentperformanceauthoring',
            name='date',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
