# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-21 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_service', '0002_auto_20170921_0640'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundHourlyCallAuthoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(max_length=255)),
                ('campaign', models.CharField(max_length=255)),
                ('skill', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('caller_no', models.CharField(max_length=255)),
                ('start_time', models.CharField(max_length=255)),
                ('time_to_answer', models.CharField(max_length=255)),
                ('end_time', models.CharField(max_length=255)),
                ('talk_time', models.CharField(max_length=255)),
                ('hold_time', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('call_flow', models.CharField(max_length=255)),
                ('agent', models.CharField(max_length=255)),
                ('wrapup_duration', models.CharField(max_length=255)),
                ('disposition', models.CharField(max_length=255)),
                ('handling_time', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('dial_status', models.CharField(max_length=255)),
                ('hangup_by', models.CharField(max_length=255)),
                ('transfer', models.CharField(max_length=255)),
                ('uui', models.CharField(default='UUI', max_length=255)),
                ('comments', models.CharField(max_length=255)),
                ('audio_url', models.CharField(max_length=255)),
                ('sheet_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OutboundHourlyCallAuthoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(max_length=255)),
                ('campaign', models.CharField(max_length=255)),
                ('call_type', models.CharField(max_length=255)),
                ('called_no', models.CharField(max_length=255)),
                ('start_time', models.CharField(max_length=255)),
                ('end_time', models.CharField(max_length=255)),
                ('talk_time', models.CharField(max_length=255)),
                ('hold_time', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('wrapup_duration', models.CharField(max_length=255)),
                ('handling_time', models.CharField(max_length=255)),
                ('call_flow', models.CharField(max_length=255)),
                ('disposition', models.CharField(max_length=255)),
                ('dial_status', models.CharField(max_length=255)),
                ('customer_dial_status', models.CharField(max_length=255)),
                ('agent_dial_status', models.CharField(max_length=255)),
                ('hangup_by', models.CharField(max_length=255)),
                ('transfer', models.CharField(max_length=255)),
                ('uui', models.CharField(default='UUI', max_length=255)),
                ('comments', models.CharField(max_length=255)),
                ('audio_url', models.CharField(max_length=255)),
                ('sheet_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='InboundHourlyCallsAuthoring',
        ),
        migrations.DeleteModel(
            name='OutboundHourlyCallsAuthoring',
        ),
        migrations.AlterField(
            model_name='inboundhourlycall',
            name='time_to_answer',
            field=models.IntegerField(blank=True),
        ),
    ]
