# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-01-29 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_service', '0003_inbounddaily_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboundhourlycall',
            name='call_id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
