# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-28 09:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170928_0923'),
        ('voice_service', '0003_auto_20170921_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundDaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_worked', models.IntegerField(default=0)),
                ('total_calls', models.IntegerField()),
                ('connects_per_hr', models.IntegerField()),
                ('calls_answered', models.IntegerField()),
                ('wrapup_time', models.IntegerField(default=0)),
                ('hold_time', models.IntegerField(default=0)),
                ('talk_time', models.IntegerField(default=0)),
                ('time_to_answer', models.IntegerField(default=0)),
                ('skill', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('disposition', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InboundDailyAuthoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(blank=True, max_length=255)),
                ('hours_worked', models.CharField(blank=True, max_length=255)),
                ('calls', models.CharField(blank=True, max_length=255)),
                ('connects_per_hr', models.CharField(blank=True, max_length=255)),
                ('calls_answered', models.CharField(blank=True, max_length=255)),
                ('wrapup_time', models.CharField(blank=True, max_length=255)),
                ('hold_time', models.CharField(blank=True, max_length=255)),
                ('talk_time', models.CharField(blank=True, max_length=255)),
                ('time_to_answer', models.CharField(blank=True, max_length=255)),
                ('skill', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('disposition', models.CharField(blank=True, max_length=255)),
                ('sheet_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Center')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutboundDaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_worked', models.IntegerField(default=0)),
                ('total_calls', models.IntegerField()),
                ('connects_per_hr', models.IntegerField()),
                ('calls_answered', models.IntegerField()),
                ('wrapup_time', models.IntegerField(default=0)),
                ('hold_time', models.IntegerField(default=0)),
                ('talk_time', models.IntegerField(default=0)),
                ('time_to_answer', models.IntegerField(default=0)),
                ('disposition', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutboundDailyAuthoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(blank=True, max_length=255)),
                ('hours_worked', models.CharField(blank=True, max_length=255)),
                ('calls', models.CharField(blank=True, max_length=255)),
                ('connects_per_hr', models.CharField(blank=True, max_length=255)),
                ('calls_answered', models.CharField(blank=True, max_length=255)),
                ('wrapup_time', models.CharField(blank=True, max_length=255)),
                ('hold_time', models.CharField(blank=True, max_length=255)),
                ('talk_time', models.CharField(blank=True, max_length=255)),
                ('time_to_answer', models.CharField(blank=True, max_length=255)),
                ('disposition', models.CharField(blank=True, max_length=255)),
                ('sheet_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Center')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Project')),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='agenttransfercall',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='agenttransfercall',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='inbounddailycall',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='inbounddailycall',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='inboundhourlycall',
            name='call_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='inboundhourlycall',
            name='center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Center'),
        ),
        migrations.AddField(
            model_name='inboundhourlycall',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='inboundhourlycall',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Project'),
        ),
        migrations.AddField(
            model_name='inboundhourlycall',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='inboundhourlycallauthoring',
            name='call_date',
            field=models.CharField(default='Call Date', max_length=255),
        ),
        migrations.AddField(
            model_name='inboundhourlycallauthoring',
            name='center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Center'),
        ),
        migrations.AddField(
            model_name='inboundhourlycallauthoring',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='inboundhourlycallauthoring',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Project'),
        ),
        migrations.AddField(
            model_name='inboundhourlycallauthoring',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='outbounddailycall',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='outbounddailycall',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='outboundhourlycall',
            name='call_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='outboundhourlycall',
            name='center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Center'),
        ),
        migrations.AddField(
            model_name='outboundhourlycall',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='outboundhourlycall',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Project'),
        ),
        migrations.AddField(
            model_name='outboundhourlycall',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='outboundhourlycallauthoring',
            name='call_date',
            field=models.CharField(default='Call Date', max_length=255),
        ),
        migrations.AddField(
            model_name='outboundhourlycallauthoring',
            name='center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Center'),
        ),
        migrations.AddField(
            model_name='outboundhourlycallauthoring',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='outboundhourlycallauthoring',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Project'),
        ),
        migrations.AddField(
            model_name='outboundhourlycallauthoring',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='skilltransfercall',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='skilltransfercall',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='inboundhourlycall',
            name='end_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inboundhourlycall',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inboundhourlycall',
            name='skill',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inboundhourlycall',
            name='start_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='locationtransfercall',
            name='from_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_locations', to='voice_service.Location'),
        ),
        migrations.AlterField(
            model_name='locationtransfercall',
            name='to_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_locations', to='voice_service.Location'),
        ),
        migrations.AddField(
            model_name='outbounddaily',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_daily_agents', to='voice_service.Agent'),
        ),
        migrations.AddField(
            model_name='outbounddaily',
            name='center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Center'),
        ),
        migrations.AddField(
            model_name='outbounddaily',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Project'),
        ),
        migrations.AddField(
            model_name='inbounddaily',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_daily_agents', to='voice_service.Agent'),
        ),
        migrations.AddField(
            model_name='inbounddaily',
            name='center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Center'),
        ),
        migrations.AddField(
            model_name='inbounddaily',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Project'),
        ),
    ]
