# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-01-29 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voice_service', '0004_auto_20180129_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositiontransfercall',
            name='call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disposition_transfer_callss', to='voice_service.InboundHourlyCall'),
        ),
        migrations.AlterField(
            model_name='inboundhourlycall',
            name='call_id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
