# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-01-29 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voice_service', '0005_auto_20180129_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispositiontransfercall',
            name='call',
        ),
    ]
