# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-28 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voice_service', '0005_auto_20170928_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='updated_at',
        ),
    ]
