# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-28 09:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voice_service', '0006_auto_20170928_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbounddailycall',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='inbounddailycall',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='inboundhourlycall',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='inboundhourlycall',
            name='updated_at',
        ),
    ]
