# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-28 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voice_service', '0007_auto_20170928_0940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inboundhourlycallauthoring',
            old_name='call_date',
            new_name='date',
        ),
    ]
