# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-28 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_service', '0008_auto_20170928_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboundhourlycallauthoring',
            name='date',
            field=models.CharField(max_length=255),
        ),
    ]
