# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-28 09:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_service', '0010_auto_20170928_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundhourlycallauthoring',
            name='call_date',
            field=models.CharField(default='Call Date', max_length=255),
        ),
        migrations.AddField(
            model_name='outboundhourlycall',
            name='call_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='outboundhourlycallauthoring',
            name='call_date',
            field=models.CharField(default='Call Date', max_length=255),
        ),
    ]
