# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-28 10:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voice_service', '0011_auto_20170928_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inboundhourlycallauthoring',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='inboundhourlycallauthoring',
            name='updated_at',
        ),
    ]
