# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-29 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_service', '0013_auto_20170928_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbounddaily',
            name='call_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='inbounddailyauthoring',
            name='call_date',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='outbounddaily',
            name='call_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='outbounddailyauthoring',
            name='call_date',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
