# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-10-09 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_widgets_group_display_value'),
        ('voice_service', '0014_auto_20170929_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('call_type', models.CharField(blank=True, max_length=255)),
                ('total_calls', models.IntegerField(default=0)),
                ('connected_calls', models.IntegerField(default=0)),
                ('abandoned_calls', models.IntegerField(default=0)),
                ('talk_time', models.IntegerField(default=0)),
                ('wrapup_time', models.IntegerField(default=0)),
                ('pause_time', models.IntegerField(default=0)),
                ('idle_time', models.IntegerField(default=0)),
                ('login_duration', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_performance_agents', to='voice_service.Agent')),
                ('center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Center')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Project')),
            ],
        ),
        migrations.CreateModel(
            name='AgentPerformanceAuthoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=255)),
                ('agent', models.CharField(blank=True, max_length=255)),
                ('call_type', models.CharField(blank=True, max_length=255)),
                ('total_calls', models.CharField(blank=True, max_length=255)),
                ('connected_calls', models.CharField(blank=True, max_length=255)),
                ('abandoned_calls', models.CharField(blank=True, max_length=255)),
                ('talk_time', models.CharField(blank=True, max_length=255)),
                ('wrapup_time', models.CharField(blank=True, max_length=255)),
                ('pause_time', models.CharField(blank=True, max_length=255)),
                ('idle_time', models.CharField(blank=True, max_length=255)),
                ('login_duration', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Center')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Project')),
            ],
        ),
    ]
