# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-10-11 06:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voice_service', '0015_agentperformance_agentperformanceauthoring'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='inbounddailycall',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='inbounddailycall',
            name='agent',
        ),
        migrations.AlterIndexTogether(
            name='outbounddailycall',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='outbounddailycall',
            name='agent',
        ),
        migrations.AddField(
            model_name='locationtransfercall',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='locationtransfercall',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='inboundhourlycall',
            name='inbound_daily_calls',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_calls', to='voice_service.InboundDaily'),
        ),
        migrations.AlterField(
            model_name='locationtransfercall',
            name='from_location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='locationtransfercall',
            name='to_location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='outboundhourlycall',
            name='outbound_daily_calls',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_calls', to='voice_service.OutboundDaily'),
        ),
        migrations.AlterField(
            model_name='skilltransfercall',
            name='from_skill',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='skilltransfercall',
            name='to_skill',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='InboundDailyCall',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='OutboundDailyCall',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
