# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-10 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_service', '0021_dispositiontransfercall'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbounddaily',
            name='status',
            field=models.CharField(choices=[(b'Answered', b'Answered'), (b'Unanswered', b'Unanswered')], default='Answered', max_length=50),
        ),
        migrations.AlterField(
            model_name='inboundhourlycall',
            name='status',
            field=models.CharField(choices=[(b'Answered', b'Answered'), (b'Unanswered', b'Unanswered')], default='Answered', max_length=50),
        ),
    ]
