# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-11 12:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peoples_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='colorcoding',
            index_together=set([('project', 'widget', 'month')]),
        ),
    ]
