# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-28 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peoples_dashboard', '0002_auto_20170811_1204'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='colorcoding',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='colorcoding',
            name='project',
        ),
        migrations.RemoveField(
            model_name='colorcoding',
            name='widget',
        ),
        migrations.DeleteModel(
            name='ColorCoding',
        ),
    ]
